import type { Metadata } from 'next'
import Nav from '../components/Nav'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '../components/Providers'
import Footer from '../components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

      <html lang="en">
          <Provider>
              <body className={inter.className}>
        
                  <Nav />
                  {children}
                  <Footer/>
          
              </body>
            </Provider>
      </html>

  )
}
